// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package notespb

import (
	"context"

	grpc "google.golang.org/grpc"
)

type GetNoteRequest struct{ Id int64 }
type Note struct {
	Id   int64
	Body string
}
type ListNotesRequest struct{}
type ListNotesResponse struct{ Notes []*Note }

// NotesServer is the server API for Notes service.
type NotesServer interface {
	GetNote(context.Context, *GetNoteRequest) (*Note, error)
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	DeleteNote(context.Context, *GetNoteRequest) (*Note, error)
	mustEmbedUnimplementedNotesServer()
}

// UnimplementedNotesServer must be embedded to have forward compatible implementations.
type UnimplementedNotesServer struct{}

func (UnimplementedNotesServer) GetNote(context.Context, *GetNoteRequest) (*Note, error) {
	return nil, nil
}
func (UnimplementedNotesServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, nil
}
func (UnimplementedNotesServer) DeleteNote(context.Context, *GetNoteRequest) (*Note, error) {
	return nil, nil
}
func (UnimplementedNotesServer) mustEmbedUnimplementedNotesServer() {}

func RegisterNotesServer(s grpc.ServiceRegistrar, srv NotesServer) {
	s.RegisterService(&Notes_ServiceDesc, srv)
}

var Notes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.v1.Notes",
	HandlerType: (*NotesServer)(nil),
}
