// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (user_id, body) VALUES ($1, $2)
`

type CreateNoteParams struct {
	UserID int64
	Body   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote, arg.UserID, arg.Body)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name FROM users WHERE id = $1
`

type User struct {
	ID    int64
	Email string
	Name  string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, body FROM notes WHERE user_id = $1
`

type Note struct {
	ID     int64
	UserID int64
	Body   string
}

func (q *Queries) ListNotes(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.UserID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
