package analysis

import (
	"fmt"
	"go/constant"
	"go/types"
	"slices"
	"strings"
	"unicode"

	"golang.org/x/tools/go/ssa"

	"github.com/tewecske/interactivecodebase/internal/graph"
	"github.com/tewecske/interactivecodebase/internal/sqlparse"
)

// dataAccessSinks are sink rules for database libraries beyond
// database/sql: sqlx, pgx (v4 and v5) and gorm's raw SQL.
func dataAccessSinks() []SinkRule {
	var rules []SinkRule
	add := func(arg int, rebind bool, funcs ...string) {
		for _, f := range funcs {
			rules = append(rules, SinkRule{Kind: graph.KindSinkSQL, Func: f, Arg: arg, Rebind: rebind})
		}
	}

	const sqlx = "github.com/jmoiron/sqlx"
	for _, recv := range []string{"(*" + sqlx + ".DB)", "(*" + sqlx + ".Tx)", "(*" + sqlx + ".Conn)"} {
		add(0, false, recv+".Queryx", recv+".QueryRowx", recv+".MustExec", recv+".Preparex")
		add(1, false, recv+".Get", recv+".Select", recv+".QueryxContext", recv+".QueryRowxContext",
			recv+".MustExecContext", recv+".PreparexContext")
		add(2, false, recv+".GetContext", recv+".SelectContext")
		add(0, true, recv+".NamedExec", recv+".NamedQuery", recv+".PrepareNamed")
		add(1, true, recv+".NamedExecContext", recv+".NamedQueryContext", recv+".PrepareNamedContext")
	}
	add(1, true, sqlx+".NamedExec", sqlx+".NamedQuery")
	add(2, true, sqlx+".NamedExecContext", sqlx+".NamedQueryContext")
	add(1, false, sqlx+".MustExec")
	add(2, false, sqlx+".Get", sqlx+".Select", sqlx+".MustExecContext")
	add(3, false, sqlx+".GetContext", sqlx+".SelectContext")

	for _, v := range []string{"v4", "v5"} {
		pgx := "github.com/jackc/pgx/" + v
		for _, recv := range []string{
			"(*" + pgx + ".Conn)", "(*" + pgx + "/pgxpool.Pool)", "(*" + pgx + "/pgxpool.Conn)",
			"(*" + pgx + "/pgxpool.Tx)", "(*" + pgx + ".dbTx)", "(*" + pgx + ".dbSimulatedNestedTx)",
		} {
			add(1, false, recv+".Query", recv+".QueryRow", recv+".Exec")
		}
		add(2, false, "(*"+pgx+".Conn).Prepare")
		// Batched statements run at SendBatch; their SQL is queued here.
		add(0, false, "(*"+pgx+".Batch).Queue")
	}

	add(0, true, "(*gorm.io/gorm.DB).Raw", "(*gorm.io/gorm.DB).Exec")
	return rules
}

// positional rewrites named (:name, sqlx) and question-mark (?, gorm)
// parameters as positional ones ($1) so the query parses as Postgres.
// Casts (::type) and quoted text are left alone.
func positional(q string) string {
	var b strings.Builder
	n := 0
	for i := 0; i < len(q); i++ {
		c := q[i]
		switch {
		case c == '\'' || c == '"':
			j := i + 1
			for j < len(q) && q[j] != c {
				j++
			}
			b.WriteString(q[i:min(j+1, len(q))])
			i = j
		case c == '?':
			n++
			fmt.Fprintf(&b, "$%d", n)
		case c == ':' && i+1 < len(q) && q[i+1] == ':':
			b.WriteString("::")
			i++
		case c == ':' && i+1 < len(q) && (q[i+1] == '_' || unicode.IsLetter(rune(q[i+1]))):
			j := i + 1
			for j < len(q) && (q[j] == '_' || q[j] == '.' || unicode.IsLetter(rune(q[j])) || unicode.IsDigit(rune(q[j]))) {
				j++
			}
			n++
			fmt.Fprintf(&b, "$%d", n)
			i = j - 1
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}

// sqlcAnnotation marks query text generated by sqlc.
const sqlcAnnotation = "-- name: "

// sqlcSink recognizes a call through an interface passing sqlc-generated
// query text (db.DBTX when nothing in the program implements it), which
// the call graph cannot resolve to a database library.
func sqlcSink(fn *ssa.Function, call ssa.CallInstruction) (Sink, bool) {
	common := call.Common()
	if !common.IsInvoke() {
		return Sink{}, false
	}
	for _, arg := range common.Args {
		k, ok := arg.(*ssa.Const)
		if !ok || k.Value == nil || k.Value.Kind() != constant.String {
			continue
		}
		if text := constant.StringVal(k.Value); strings.HasPrefix(text, sqlcAnnotation) {
			return Sink{
				Kind: graph.KindSinkSQL, Caller: fn, Callee: common.Method.FullName(),
				Values: []string{text}, Pos: call.Pos(), Instr: call,
			}, true
		}
	}
	return Sink{}, false
}

// gorm finishers: the methods that run a statement, and what it does.
var gormFinishers = map[string][]string{
	"First": {sqlparse.OpSelect}, "Take": {sqlparse.OpSelect}, "Last": {sqlparse.OpSelect},
	"Find": {sqlparse.OpSelect}, "FindInBatches": {sqlparse.OpSelect}, "Count": {sqlparse.OpSelect},
	"Pluck": {sqlparse.OpSelect}, "Scan": {sqlparse.OpSelect}, "Row": {sqlparse.OpSelect},
	"Rows": {sqlparse.OpSelect}, "FirstOrInit": {sqlparse.OpSelect},
	"Create": {sqlparse.OpInsert}, "CreateInBatches": {sqlparse.OpInsert},
	"Save": {sqlparse.OpInsert, sqlparse.OpUpdate}, "FirstOrCreate": {sqlparse.OpSelect, sqlparse.OpInsert},
	"Update": {sqlparse.OpUpdate}, "Updates": {sqlparse.OpUpdate}, "UpdateColumn": {sqlparse.OpUpdate},
	"UpdateColumns": {sqlparse.OpUpdate},
	"Delete":        {sqlparse.OpDelete},
}

// gormDestArg reports which finishers take the model (or a slice of it)
// as their first argument.
var gormDestArg = map[string]bool{
	"First": true, "Take": true, "Last": true, "Find": true, "FindInBatches": true, "FirstOrInit": true,
	"Create": true, "CreateInBatches": true, "Save": true, "FirstOrCreate": true, "Delete": true,
}

const gormDB = "(*gorm.io/gorm.DB)."

// gormSink turns a gorm finisher call into an SQL sink whose tables come
// from the model it is given or the Model/Table calls chained before it.
// Chains starting from Raw or Exec are left to the raw-SQL rules.
func gormSink(ev *evaluator, fn *ssa.Function, call *ssa.Call) (Sink, bool) {
	callee := call.Common().StaticCallee()
	if callee == nil {
		return Sink{}, false
	}
	name, ok := strings.CutPrefix(callee.String(), gormDB)
	if !ok {
		return Sink{}, false
	}
	ops, ok := gormFinishers[name]
	if !ok {
		return Sink{}, false
	}
	args := call.Common().Args
	tables, raw := gormChain(ev, args[0], 0)
	if raw {
		return Sink{}, false
	}
	if len(tables) == 0 && len(args) > 1 && (gormDestArg[name] || name == "Updates") {
		if t := gormTable(fn.Prog, args[1]); t != "" {
			tables = []string{t}
		}
	}
	var columns []string
	if (name == "Update" || name == "UpdateColumn" || name == "Pluck") && len(args) > 1 {
		if cols := ev.strings(args[1]); !slices.Contains(cols, Unknown) {
			columns = cols
		}
	}
	q := &sqlparse.Query{Ops: ops}
	var values []string
	for _, t := range tables {
		for _, op := range ops {
			q.Tables = append(q.Tables, sqlparse.TableUse{Name: t, Op: op, Columns: columns})
		}
		values = append(values, fmt.Sprintf("-- gorm %s\n%s %s", name, strings.ToUpper(strings.Join(ops, "/")), t))
	}
	if len(tables) == 0 {
		q.Partial = true
		values = []string{fmt.Sprintf("-- gorm %s\n%s %s", name, strings.ToUpper(strings.Join(ops, "/")), Unknown)}
	}
	return Sink{
		Kind: graph.KindSinkSQL, Caller: fn, Callee: callee.String(), Values: values,
		Pos: call.Pos(), Instr: call, Query: q,
	}, true
}

// gormChain walks the calls a *gorm.DB went through, collecting tables
// named by Table("t") or Model(&T{}). raw reports a Raw or Exec in the
// chain.
func gormChain(ev *evaluator, v ssa.Value, depth int) (tables []string, raw bool) {
	if depth > maxEvalDepth {
		return nil, false
	}
	switch v := v.(type) {
	case *ssa.Phi:
		for _, e := range v.Edges {
			t, r := gormChain(ev, e, depth+1)
			tables, raw = union(tables, t), raw || r
		}
		return tables, raw
	case *ssa.Call:
		callee := v.Common().StaticCallee()
		if callee == nil {
			return nil, false
		}
		name, ok := strings.CutPrefix(callee.String(), gormDB)
		if !ok || len(v.Common().Args) == 0 {
			return nil, false
		}
		tables, raw = gormChain(ev, v.Common().Args[0], depth+1)
		switch name {
		case "Raw", "Exec":
			raw = true
		case "Table":
			if len(v.Common().Args) > 1 {
				if names := ev.strings(v.Common().Args[1]); !slices.Contains(names, Unknown) {
					tables = names
				}
			}
		case "Model":
			if len(v.Common().Args) > 1 {
				if t := gormTable(v.Parent().Prog, v.Common().Args[1]); t != "" {
					tables = []string{t}
				}
			}
		}
		return tables, raw
	}
	return nil, false
}

// gormTable names the table of a model value: *T, *[]T or *[]*T for a
// struct T, named by its TableName method or gorm's naming convention
// (snake_case, plural).
func gormTable(prog *ssa.Program, v ssa.Value) string {
	if mi, ok := v.(*ssa.MakeInterface); ok {
		v = mi.X
	}
	t := v.Type()
	for {
		switch u := types.Unalias(t).(type) {
		case *types.Pointer:
			t = u.Elem()
			continue
		case *types.Slice:
			t = u.Elem()
			continue
		}
		break
	}
	named, ok := types.Unalias(t).(*types.Named)
	if !ok {
		return ""
	}
	if _, ok := named.Underlying().(*types.Struct); !ok {
		return ""
	}
	for _, recv := range []types.Type{named, types.NewPointer(named)} {
		sel := prog.MethodSets.MethodSet(recv).Lookup(named.Obj().Pkg(), "TableName")
		if sel == nil {
			continue
		}
		if fn := prog.MethodValue(sel); fn != nil {
			for _, ret := range returns(fn) {
				if k, ok := ret.(*ssa.Const); ok && k.Value != nil && k.Value.Kind() == constant.String {
					return constant.StringVal(k.Value)
				}
			}
		}
	}
	return plural(snakeCase(named.Obj().Name()))
}

// snakeCase converts a Go name as gorm does: UserID -> user_id,
// HTTPServer -> http_server.
func snakeCase(name string) string {
	rs := []rune(name)
	var b strings.Builder
	for i, r := range rs {
		if unicode.IsUpper(r) {
			if i > 0 && (unicode.IsLower(rs[i-1]) || unicode.IsDigit(rs[i-1]) ||
				(i+1 < len(rs) && unicode.IsLower(rs[i+1]) && unicode.IsUpper(rs[i-1]))) {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// plural makes an English plural the way gorm's inflection does for
// common words.
func plural(word string) string {
	irregular := map[string]string{"person": "people", "man": "men", "woman": "women", "child": "children", "mouse": "mice"}
	head, last := "", word
	if i := strings.LastIndexByte(word, '_'); i >= 0 {
		head, last = word[:i+1], word[i+1:]
	}
	if p, ok := irregular[last]; ok {
		return head + p
	}
	switch {
	case strings.HasSuffix(word, "y") && len(word) > 1 && !strings.ContainsRune("aeiou", rune(word[len(word)-2])):
		return word[:len(word)-1] + "ies"
	case strings.HasSuffix(word, "s"), strings.HasSuffix(word, "x"), strings.HasSuffix(word, "z"),
		strings.HasSuffix(word, "ch"), strings.HasSuffix(word, "sh"):
		return word + "es"
	}
	return word + "s"
}
